### ISSUE TITLE
Doing the classes final is a bad decision

### ISSUE THREAD

**Issue by jhonatanTeixeira** [zf-fr/hydrator#12]
caching should be done in a decoupled way like a cached strategy or something external to the classes. Besides, caching should be something optional since it's not always welcome on a development environment.

Final classes are a pain to testing since you can't mock them.

Also, a framework like zf2 or 3 is totaly extendable, even tho i don't like to extend concrete classes a framework shouldn't get on the developers way, it is meant to bend to the developers will.

**Comment by ojhaujjwal** [comment]
If you have to mock a hydrator class, you are doing it wrong in the first place.
The class you are testing should expect `HydratorInterface` and not a specific implementation of hydrator. That way, you can just mock that interface.

**Comment by Ocramius** [comment]
As @ojhaujjwal said, you shouldn't mock concrete types, but abstract types (abstract classes and interfaces) instead.

As a reference, consider reading http://ocramius.github.io/blog/when-to-declare-classes-final/ - I know I am biased as an author, but I include clear decision paths on when to use `final` and when not to.
